version: '3.8'

services:
  api:
    user: root
    container_name: sales-service-dev
    image: sales-service-dev:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8084
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./target:/app/target
    command: mvn spring-boot:run
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/"]
      interval: 50s
      timeout: 10s
      retries: 5
      start_period: 40s