version: '3.8'

services:
  api:
    container_name: customers-service-prod
    image: customers-service:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    working_dir: /app
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8085
    command: java -jar app.jar
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/"]
      interval: 50s
      timeout: 10s
      retries: 5
      start_period: 40s